using System;
using System.IO;
using System.Linq;
using UnityEngine;

namespace Stator.Editor
{
    public class StatorSettings
    {
        public const string CONFIG_NAME = ".stator";
        public string PathToGenerate { get; set; }
        public bool EnableDebugging { get; set; }
        public bool DisabledAutoRefreshing { get; set; }
        public string AutoGeneratedFolder { get; set; }

        public StatorSettings()
        {
            AutoGeneratedFolder = "stator_builders";

            var configPath = Path.Combine(Application.dataPath, "..", CONFIG_NAME);
            if(File.Exists(configPath))
            {
                var configs = File.ReadAllLines(configPath)
                    .Where(l => !string.IsNullOrWhiteSpace(l))
                    .Select(l => l.Split(new []{'='}, StringSplitOptions.RemoveEmptyEntries).Select(s => s.Trim()).ToArray())
                    .Where(l => l.Count() == 2)
                    .ToDictionary(l => l[0], l => l[1]);
                
                if(configs.TryGetValue(nameof(AutoGeneratedFolder), out var _autoGeneratedFolder))
                {
                    AutoGeneratedFolder = _autoGeneratedFolder;
                }

                if(configs.TryGetValue(nameof(EnableDebugging), out var _enableDebugging)
                    && bool.TryParse(_enableDebugging, out var enabledDebugging))
                {
                    EnableDebugging = enabledDebugging;
                }

                if(configs.TryGetValue(nameof(DisabledAutoRefreshing), out var _dar)
                    && bool.TryParse(_enableDebugging, out var _value_dar))
                {
                    DisabledAutoRefreshing = _value_dar;
                }
            }

            PathToGenerate = Path.Combine(Application.dataPath, AutoGeneratedFolder);
        }
    }
}